title: "Brittanne Peterkin-Walker"
email: brittannep95@gmail.com
description: >-
  Welcome to my portfolio
baseurl: ""
url: "https://brittannep.github.io"
github_username: brittannep
minimal_mistakes_skin: default
search: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

include:
  - _pages

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: single
      author_profile: true

markdown: kramdown
theme: minimal-mistakes-jekyll

# Custom CSS and JS
sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      css: assets/css/custom.css
      js: assets/js/custom.js