title: "Your Name"
email: your-email@example.com
description: >-
  A personal portfolio website built with Minimal Mistakes.
baseurl: ""
url: "https://yourusername.github.io"
twitter_username: yourhandle
github_username: yourusername
minimal_mistakes_skin: default
search: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

include:
  - _pages

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: single
      author_profile: true

markdown: kramdown
theme: minimal-mistakes-jekyll

# Custom CSS and JS
sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      css: assets/css/custom.css
      js: assets/js/custom.js